// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: tracks.proto

package trackspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp float64                `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // seconds from start of file
	// Types that are valid to be assigned to Event:
	//
	//	*Envelope_TrackStart
	//	*Envelope_TrackEnd
	//	*Envelope_TrackPosition
	//	*Envelope_TrackAbort
	//	*Envelope_Beat
	//	*Envelope_TempoChange
	//	*Envelope_Downbeat
	//	*Envelope_Onset
	//	*Envelope_OnsetRate
	//	*Envelope_Novelty
	//	*Envelope_KeyChange
	//	*Envelope_ChordChange
	//	*Envelope_Chroma
	//	*Envelope_Tuning
	//	*Envelope_Dissonance
	//	*Envelope_Inharmonicity
	//	*Envelope_Pitch
	//	*Envelope_PitchChange
	//	*Envelope_Melody
	//	*Envelope_Loudness
	//	*Envelope_LoudnessPeak
	//	*Envelope_Energy
	//	*Envelope_DynamicChange
	//	*Envelope_SilenceStart
	//	*Envelope_SilenceEnd
	//	*Envelope_Gap
	//	*Envelope_SpectralCentroid
	//	*Envelope_SpectralFlux
	//	*Envelope_SpectralComplexity
	//	*Envelope_SpectralContrast
	//	*Envelope_SpectralRolloff
	//	*Envelope_Mfcc
	//	*Envelope_TimbreChange
	//	*Envelope_BandsMel
	//	*Envelope_BandsBark
	//	*Envelope_BandsErb
	//	*Envelope_Hfc
	//	*Envelope_SegmentBoundary
	//	*Envelope_FadeIn
	//	*Envelope_FadeOut
	//	*Envelope_Click
	//	*Envelope_Discontinuity
	//	*Envelope_NoiseBurst
	//	*Envelope_Saturation
	//	*Envelope_Hum
	//	*Envelope_EnvelopeEvent
	//	*Envelope_Attack
	//	*Envelope_Decay
	Event         isEnvelope_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_tracks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetEvent() isEnvelope_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Envelope) GetTrackStart() *TrackStart {
	if x != nil {
		if x, ok := x.Event.(*Envelope_TrackStart); ok {
			return x.TrackStart
		}
	}
	return nil
}

func (x *Envelope) GetTrackEnd() *TrackEnd {
	if x != nil {
		if x, ok := x.Event.(*Envelope_TrackEnd); ok {
			return x.TrackEnd
		}
	}
	return nil
}

func (x *Envelope) GetTrackPosition() *TrackPosition {
	if x != nil {
		if x, ok := x.Event.(*Envelope_TrackPosition); ok {
			return x.TrackPosition
		}
	}
	return nil
}

func (x *Envelope) GetTrackAbort() *TrackAbort {
	if x != nil {
		if x, ok := x.Event.(*Envelope_TrackAbort); ok {
			return x.TrackAbort
		}
	}
	return nil
}

func (x *Envelope) GetBeat() *Beat {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Beat); ok {
			return x.Beat
		}
	}
	return nil
}

func (x *Envelope) GetTempoChange() *TempoChange {
	if x != nil {
		if x, ok := x.Event.(*Envelope_TempoChange); ok {
			return x.TempoChange
		}
	}
	return nil
}

func (x *Envelope) GetDownbeat() *Downbeat {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Downbeat); ok {
			return x.Downbeat
		}
	}
	return nil
}

func (x *Envelope) GetOnset() *Onset {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Onset); ok {
			return x.Onset
		}
	}
	return nil
}

func (x *Envelope) GetOnsetRate() *OnsetRate {
	if x != nil {
		if x, ok := x.Event.(*Envelope_OnsetRate); ok {
			return x.OnsetRate
		}
	}
	return nil
}

func (x *Envelope) GetNovelty() *Novelty {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Novelty); ok {
			return x.Novelty
		}
	}
	return nil
}

func (x *Envelope) GetKeyChange() *KeyChange {
	if x != nil {
		if x, ok := x.Event.(*Envelope_KeyChange); ok {
			return x.KeyChange
		}
	}
	return nil
}

func (x *Envelope) GetChordChange() *ChordChange {
	if x != nil {
		if x, ok := x.Event.(*Envelope_ChordChange); ok {
			return x.ChordChange
		}
	}
	return nil
}

func (x *Envelope) GetChroma() *Chroma {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Chroma); ok {
			return x.Chroma
		}
	}
	return nil
}

func (x *Envelope) GetTuning() *Tuning {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Tuning); ok {
			return x.Tuning
		}
	}
	return nil
}

func (x *Envelope) GetDissonance() *Dissonance {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Dissonance); ok {
			return x.Dissonance
		}
	}
	return nil
}

func (x *Envelope) GetInharmonicity() *Inharmonicity {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Inharmonicity); ok {
			return x.Inharmonicity
		}
	}
	return nil
}

func (x *Envelope) GetPitch() *Pitch {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Pitch); ok {
			return x.Pitch
		}
	}
	return nil
}

func (x *Envelope) GetPitchChange() *PitchChange {
	if x != nil {
		if x, ok := x.Event.(*Envelope_PitchChange); ok {
			return x.PitchChange
		}
	}
	return nil
}

func (x *Envelope) GetMelody() *Melody {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Melody); ok {
			return x.Melody
		}
	}
	return nil
}

func (x *Envelope) GetLoudness() *Loudness {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Loudness); ok {
			return x.Loudness
		}
	}
	return nil
}

func (x *Envelope) GetLoudnessPeak() *LoudnessPeak {
	if x != nil {
		if x, ok := x.Event.(*Envelope_LoudnessPeak); ok {
			return x.LoudnessPeak
		}
	}
	return nil
}

func (x *Envelope) GetEnergy() *Energy {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Energy); ok {
			return x.Energy
		}
	}
	return nil
}

func (x *Envelope) GetDynamicChange() *DynamicChange {
	if x != nil {
		if x, ok := x.Event.(*Envelope_DynamicChange); ok {
			return x.DynamicChange
		}
	}
	return nil
}

func (x *Envelope) GetSilenceStart() *SilenceStart {
	if x != nil {
		if x, ok := x.Event.(*Envelope_SilenceStart); ok {
			return x.SilenceStart
		}
	}
	return nil
}

func (x *Envelope) GetSilenceEnd() *SilenceEnd {
	if x != nil {
		if x, ok := x.Event.(*Envelope_SilenceEnd); ok {
			return x.SilenceEnd
		}
	}
	return nil
}

func (x *Envelope) GetGap() *Gap {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Gap); ok {
			return x.Gap
		}
	}
	return nil
}

func (x *Envelope) GetSpectralCentroid() *SpectralCentroid {
	if x != nil {
		if x, ok := x.Event.(*Envelope_SpectralCentroid); ok {
			return x.SpectralCentroid
		}
	}
	return nil
}

func (x *Envelope) GetSpectralFlux() *SpectralFlux {
	if x != nil {
		if x, ok := x.Event.(*Envelope_SpectralFlux); ok {
			return x.SpectralFlux
		}
	}
	return nil
}

func (x *Envelope) GetSpectralComplexity() *SpectralComplexity {
	if x != nil {
		if x, ok := x.Event.(*Envelope_SpectralComplexity); ok {
			return x.SpectralComplexity
		}
	}
	return nil
}

func (x *Envelope) GetSpectralContrast() *SpectralContrast {
	if x != nil {
		if x, ok := x.Event.(*Envelope_SpectralContrast); ok {
			return x.SpectralContrast
		}
	}
	return nil
}

func (x *Envelope) GetSpectralRolloff() *SpectralRolloff {
	if x != nil {
		if x, ok := x.Event.(*Envelope_SpectralRolloff); ok {
			return x.SpectralRolloff
		}
	}
	return nil
}

func (x *Envelope) GetMfcc() *Mfcc {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Mfcc); ok {
			return x.Mfcc
		}
	}
	return nil
}

func (x *Envelope) GetTimbreChange() *TimbreChange {
	if x != nil {
		if x, ok := x.Event.(*Envelope_TimbreChange); ok {
			return x.TimbreChange
		}
	}
	return nil
}

func (x *Envelope) GetBandsMel() *BandsMel {
	if x != nil {
		if x, ok := x.Event.(*Envelope_BandsMel); ok {
			return x.BandsMel
		}
	}
	return nil
}

func (x *Envelope) GetBandsBark() *BandsBark {
	if x != nil {
		if x, ok := x.Event.(*Envelope_BandsBark); ok {
			return x.BandsBark
		}
	}
	return nil
}

func (x *Envelope) GetBandsErb() *BandsErb {
	if x != nil {
		if x, ok := x.Event.(*Envelope_BandsErb); ok {
			return x.BandsErb
		}
	}
	return nil
}

func (x *Envelope) GetHfc() *Hfc {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Hfc); ok {
			return x.Hfc
		}
	}
	return nil
}

func (x *Envelope) GetSegmentBoundary() *SegmentBoundary {
	if x != nil {
		if x, ok := x.Event.(*Envelope_SegmentBoundary); ok {
			return x.SegmentBoundary
		}
	}
	return nil
}

func (x *Envelope) GetFadeIn() *FadeIn {
	if x != nil {
		if x, ok := x.Event.(*Envelope_FadeIn); ok {
			return x.FadeIn
		}
	}
	return nil
}

func (x *Envelope) GetFadeOut() *FadeOut {
	if x != nil {
		if x, ok := x.Event.(*Envelope_FadeOut); ok {
			return x.FadeOut
		}
	}
	return nil
}

func (x *Envelope) GetClick() *Click {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Click); ok {
			return x.Click
		}
	}
	return nil
}

func (x *Envelope) GetDiscontinuity() *Discontinuity {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Discontinuity); ok {
			return x.Discontinuity
		}
	}
	return nil
}

func (x *Envelope) GetNoiseBurst() *NoiseBurst {
	if x != nil {
		if x, ok := x.Event.(*Envelope_NoiseBurst); ok {
			return x.NoiseBurst
		}
	}
	return nil
}

func (x *Envelope) GetSaturation() *Saturation {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Saturation); ok {
			return x.Saturation
		}
	}
	return nil
}

func (x *Envelope) GetHum() *Hum {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Hum); ok {
			return x.Hum
		}
	}
	return nil
}

func (x *Envelope) GetEnvelopeEvent() *EnvelopeEvent {
	if x != nil {
		if x, ok := x.Event.(*Envelope_EnvelopeEvent); ok {
			return x.EnvelopeEvent
		}
	}
	return nil
}

func (x *Envelope) GetAttack() *Attack {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Attack); ok {
			return x.Attack
		}
	}
	return nil
}

func (x *Envelope) GetDecay() *Decay {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Decay); ok {
			return x.Decay
		}
	}
	return nil
}

type isEnvelope_Event interface {
	isEnvelope_Event()
}

type Envelope_TrackStart struct {
	// Transport 10-19
	TrackStart *TrackStart `protobuf:"bytes,10,opt,name=track_start,json=trackStart,proto3,oneof"`
}

type Envelope_TrackEnd struct {
	TrackEnd *TrackEnd `protobuf:"bytes,11,opt,name=track_end,json=trackEnd,proto3,oneof"`
}

type Envelope_TrackPosition struct {
	TrackPosition *TrackPosition `protobuf:"bytes,12,opt,name=track_position,json=trackPosition,proto3,oneof"`
}

type Envelope_TrackAbort struct {
	TrackAbort *TrackAbort `protobuf:"bytes,13,opt,name=track_abort,json=trackAbort,proto3,oneof"`
}

type Envelope_Beat struct {
	// Beat/Rhythm 20-29
	Beat *Beat `protobuf:"bytes,20,opt,name=beat,proto3,oneof"`
}

type Envelope_TempoChange struct {
	TempoChange *TempoChange `protobuf:"bytes,21,opt,name=tempo_change,json=tempoChange,proto3,oneof"`
}

type Envelope_Downbeat struct {
	Downbeat *Downbeat `protobuf:"bytes,22,opt,name=downbeat,proto3,oneof"`
}

type Envelope_Onset struct {
	// Onset 30-39
	Onset *Onset `protobuf:"bytes,30,opt,name=onset,proto3,oneof"`
}

type Envelope_OnsetRate struct {
	OnsetRate *OnsetRate `protobuf:"bytes,31,opt,name=onset_rate,json=onsetRate,proto3,oneof"`
}

type Envelope_Novelty struct {
	Novelty *Novelty `protobuf:"bytes,32,opt,name=novelty,proto3,oneof"`
}

type Envelope_KeyChange struct {
	// Tonal 40-49
	KeyChange *KeyChange `protobuf:"bytes,40,opt,name=key_change,json=keyChange,proto3,oneof"`
}

type Envelope_ChordChange struct {
	ChordChange *ChordChange `protobuf:"bytes,41,opt,name=chord_change,json=chordChange,proto3,oneof"`
}

type Envelope_Chroma struct {
	Chroma *Chroma `protobuf:"bytes,42,opt,name=chroma,proto3,oneof"`
}

type Envelope_Tuning struct {
	Tuning *Tuning `protobuf:"bytes,43,opt,name=tuning,proto3,oneof"`
}

type Envelope_Dissonance struct {
	Dissonance *Dissonance `protobuf:"bytes,44,opt,name=dissonance,proto3,oneof"`
}

type Envelope_Inharmonicity struct {
	Inharmonicity *Inharmonicity `protobuf:"bytes,45,opt,name=inharmonicity,proto3,oneof"`
}

type Envelope_Pitch struct {
	// Pitch/Melody 50-59
	Pitch *Pitch `protobuf:"bytes,50,opt,name=pitch,proto3,oneof"`
}

type Envelope_PitchChange struct {
	PitchChange *PitchChange `protobuf:"bytes,51,opt,name=pitch_change,json=pitchChange,proto3,oneof"`
}

type Envelope_Melody struct {
	Melody *Melody `protobuf:"bytes,52,opt,name=melody,proto3,oneof"`
}

type Envelope_Loudness struct {
	// Loudness/Energy 60-69
	Loudness *Loudness `protobuf:"bytes,60,opt,name=loudness,proto3,oneof"`
}

type Envelope_LoudnessPeak struct {
	LoudnessPeak *LoudnessPeak `protobuf:"bytes,61,opt,name=loudness_peak,json=loudnessPeak,proto3,oneof"`
}

type Envelope_Energy struct {
	Energy *Energy `protobuf:"bytes,62,opt,name=energy,proto3,oneof"`
}

type Envelope_DynamicChange struct {
	DynamicChange *DynamicChange `protobuf:"bytes,63,opt,name=dynamic_change,json=dynamicChange,proto3,oneof"`
}

type Envelope_SilenceStart struct {
	// Silence/Gap 70-79
	SilenceStart *SilenceStart `protobuf:"bytes,70,opt,name=silence_start,json=silenceStart,proto3,oneof"`
}

type Envelope_SilenceEnd struct {
	SilenceEnd *SilenceEnd `protobuf:"bytes,71,opt,name=silence_end,json=silenceEnd,proto3,oneof"`
}

type Envelope_Gap struct {
	Gap *Gap `protobuf:"bytes,72,opt,name=gap,proto3,oneof"`
}

type Envelope_SpectralCentroid struct {
	// Spectral 80-89
	SpectralCentroid *SpectralCentroid `protobuf:"bytes,80,opt,name=spectral_centroid,json=spectralCentroid,proto3,oneof"`
}

type Envelope_SpectralFlux struct {
	SpectralFlux *SpectralFlux `protobuf:"bytes,81,opt,name=spectral_flux,json=spectralFlux,proto3,oneof"`
}

type Envelope_SpectralComplexity struct {
	SpectralComplexity *SpectralComplexity `protobuf:"bytes,82,opt,name=spectral_complexity,json=spectralComplexity,proto3,oneof"`
}

type Envelope_SpectralContrast struct {
	SpectralContrast *SpectralContrast `protobuf:"bytes,83,opt,name=spectral_contrast,json=spectralContrast,proto3,oneof"`
}

type Envelope_SpectralRolloff struct {
	SpectralRolloff *SpectralRolloff `protobuf:"bytes,84,opt,name=spectral_rolloff,json=spectralRolloff,proto3,oneof"`
}

type Envelope_Mfcc struct {
	Mfcc *Mfcc `protobuf:"bytes,85,opt,name=mfcc,proto3,oneof"`
}

type Envelope_TimbreChange struct {
	TimbreChange *TimbreChange `protobuf:"bytes,86,opt,name=timbre_change,json=timbreChange,proto3,oneof"`
}

type Envelope_BandsMel struct {
	// Bands 90-99
	BandsMel *BandsMel `protobuf:"bytes,90,opt,name=bands_mel,json=bandsMel,proto3,oneof"`
}

type Envelope_BandsBark struct {
	BandsBark *BandsBark `protobuf:"bytes,91,opt,name=bands_bark,json=bandsBark,proto3,oneof"`
}

type Envelope_BandsErb struct {
	BandsErb *BandsErb `protobuf:"bytes,92,opt,name=bands_erb,json=bandsErb,proto3,oneof"`
}

type Envelope_Hfc struct {
	Hfc *Hfc `protobuf:"bytes,93,opt,name=hfc,proto3,oneof"`
}

type Envelope_SegmentBoundary struct {
	// Structure 100-109
	SegmentBoundary *SegmentBoundary `protobuf:"bytes,100,opt,name=segment_boundary,json=segmentBoundary,proto3,oneof"`
}

type Envelope_FadeIn struct {
	FadeIn *FadeIn `protobuf:"bytes,101,opt,name=fade_in,json=fadeIn,proto3,oneof"`
}

type Envelope_FadeOut struct {
	FadeOut *FadeOut `protobuf:"bytes,102,opt,name=fade_out,json=fadeOut,proto3,oneof"`
}

type Envelope_Click struct {
	// Quality 110-119
	Click *Click `protobuf:"bytes,110,opt,name=click,proto3,oneof"`
}

type Envelope_Discontinuity struct {
	Discontinuity *Discontinuity `protobuf:"bytes,111,opt,name=discontinuity,proto3,oneof"`
}

type Envelope_NoiseBurst struct {
	NoiseBurst *NoiseBurst `protobuf:"bytes,112,opt,name=noise_burst,json=noiseBurst,proto3,oneof"`
}

type Envelope_Saturation struct {
	Saturation *Saturation `protobuf:"bytes,113,opt,name=saturation,proto3,oneof"`
}

type Envelope_Hum struct {
	Hum *Hum `protobuf:"bytes,114,opt,name=hum,proto3,oneof"`
}

type Envelope_EnvelopeEvent struct {
	// Envelope/Transient 120-129
	EnvelopeEvent *EnvelopeEvent `protobuf:"bytes,120,opt,name=envelope_event,json=envelopeEvent,proto3,oneof"`
}

type Envelope_Attack struct {
	Attack *Attack `protobuf:"bytes,121,opt,name=attack,proto3,oneof"`
}

type Envelope_Decay struct {
	Decay *Decay `protobuf:"bytes,122,opt,name=decay,proto3,oneof"`
}

func (*Envelope_TrackStart) isEnvelope_Event() {}

func (*Envelope_TrackEnd) isEnvelope_Event() {}

func (*Envelope_TrackPosition) isEnvelope_Event() {}

func (*Envelope_TrackAbort) isEnvelope_Event() {}

func (*Envelope_Beat) isEnvelope_Event() {}

func (*Envelope_TempoChange) isEnvelope_Event() {}

func (*Envelope_Downbeat) isEnvelope_Event() {}

func (*Envelope_Onset) isEnvelope_Event() {}

func (*Envelope_OnsetRate) isEnvelope_Event() {}

func (*Envelope_Novelty) isEnvelope_Event() {}

func (*Envelope_KeyChange) isEnvelope_Event() {}

func (*Envelope_ChordChange) isEnvelope_Event() {}

func (*Envelope_Chroma) isEnvelope_Event() {}

func (*Envelope_Tuning) isEnvelope_Event() {}

func (*Envelope_Dissonance) isEnvelope_Event() {}

func (*Envelope_Inharmonicity) isEnvelope_Event() {}

func (*Envelope_Pitch) isEnvelope_Event() {}

func (*Envelope_PitchChange) isEnvelope_Event() {}

func (*Envelope_Melody) isEnvelope_Event() {}

func (*Envelope_Loudness) isEnvelope_Event() {}

func (*Envelope_LoudnessPeak) isEnvelope_Event() {}

func (*Envelope_Energy) isEnvelope_Event() {}

func (*Envelope_DynamicChange) isEnvelope_Event() {}

func (*Envelope_SilenceStart) isEnvelope_Event() {}

func (*Envelope_SilenceEnd) isEnvelope_Event() {}

func (*Envelope_Gap) isEnvelope_Event() {}

func (*Envelope_SpectralCentroid) isEnvelope_Event() {}

func (*Envelope_SpectralFlux) isEnvelope_Event() {}

func (*Envelope_SpectralComplexity) isEnvelope_Event() {}

func (*Envelope_SpectralContrast) isEnvelope_Event() {}

func (*Envelope_SpectralRolloff) isEnvelope_Event() {}

func (*Envelope_Mfcc) isEnvelope_Event() {}

func (*Envelope_TimbreChange) isEnvelope_Event() {}

func (*Envelope_BandsMel) isEnvelope_Event() {}

func (*Envelope_BandsBark) isEnvelope_Event() {}

func (*Envelope_BandsErb) isEnvelope_Event() {}

func (*Envelope_Hfc) isEnvelope_Event() {}

func (*Envelope_SegmentBoundary) isEnvelope_Event() {}

func (*Envelope_FadeIn) isEnvelope_Event() {}

func (*Envelope_FadeOut) isEnvelope_Event() {}

func (*Envelope_Click) isEnvelope_Event() {}

func (*Envelope_Discontinuity) isEnvelope_Event() {}

func (*Envelope_NoiseBurst) isEnvelope_Event() {}

func (*Envelope_Saturation) isEnvelope_Event() {}

func (*Envelope_Hum) isEnvelope_Event() {}

func (*Envelope_EnvelopeEvent) isEnvelope_Event() {}

func (*Envelope_Attack) isEnvelope_Event() {}

func (*Envelope_Decay) isEnvelope_Event() {}

type TrackStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Duration      float64                `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      int32                  `protobuf:"varint,4,opt,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackStart) Reset() {
	*x = TrackStart{}
	mi := &file_tracks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackStart) ProtoMessage() {}

func (x *TrackStart) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackStart.ProtoReflect.Descriptor instead.
func (*TrackStart) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{1}
}

func (x *TrackStart) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TrackStart) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TrackStart) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *TrackStart) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

type TrackEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEnd) Reset() {
	*x = TrackEnd{}
	mi := &file_tracks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEnd) ProtoMessage() {}

func (x *TrackEnd) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEnd.ProtoReflect.Descriptor instead.
func (*TrackEnd) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{2}
}

type TrackPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      float64                `protobuf:"fixed64,1,opt,name=position,proto3" json:"position,omitempty"` // current time in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPosition) Reset() {
	*x = TrackPosition{}
	mi := &file_tracks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPosition) ProtoMessage() {}

func (x *TrackPosition) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPosition.ProtoReflect.Descriptor instead.
func (*TrackPosition) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{3}
}

func (x *TrackPosition) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

type TrackAbort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // e.g. "user_interrupt"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackAbort) Reset() {
	*x = TrackAbort{}
	mi := &file_tracks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackAbort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackAbort) ProtoMessage() {}

func (x *TrackAbort) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackAbort.ProtoReflect.Descriptor instead.
func (*TrackAbort) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{4}
}

func (x *TrackAbort) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Beat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confidence    float64                `protobuf:"fixed64,1,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Beat) Reset() {
	*x = Beat{}
	mi := &file_tracks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Beat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beat) ProtoMessage() {}

func (x *Beat) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beat.ProtoReflect.Descriptor instead.
func (*Beat) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{5}
}

func (x *Beat) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type TempoChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bpm           float64                `protobuf:"fixed64,1,opt,name=bpm,proto3" json:"bpm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempoChange) Reset() {
	*x = TempoChange{}
	mi := &file_tracks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempoChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempoChange) ProtoMessage() {}

func (x *TempoChange) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempoChange.ProtoReflect.Descriptor instead.
func (*TempoChange) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{6}
}

func (x *TempoChange) GetBpm() float64 {
	if x != nil {
		return x.Bpm
	}
	return 0
}

type Downbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confidence    float64                `protobuf:"fixed64,1,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Downbeat) Reset() {
	*x = Downbeat{}
	mi := &file_tracks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Downbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Downbeat) ProtoMessage() {}

func (x *Downbeat) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Downbeat.ProtoReflect.Descriptor instead.
func (*Downbeat) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{7}
}

func (x *Downbeat) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type Onset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strength      float64                `protobuf:"fixed64,1,opt,name=strength,proto3" json:"strength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Onset) Reset() {
	*x = Onset{}
	mi := &file_tracks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Onset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Onset) ProtoMessage() {}

func (x *Onset) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Onset.ProtoReflect.Descriptor instead.
func (*Onset) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{8}
}

func (x *Onset) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

type OnsetRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          float64                `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"` // onsets per second
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnsetRate) Reset() {
	*x = OnsetRate{}
	mi := &file_tracks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnsetRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnsetRate) ProtoMessage() {}

func (x *OnsetRate) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnsetRate.ProtoReflect.Descriptor instead.
func (*OnsetRate) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{9}
}

func (x *OnsetRate) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type Novelty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Novelty) Reset() {
	*x = Novelty{}
	mi := &file_tracks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Novelty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Novelty) ProtoMessage() {}

func (x *Novelty) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Novelty.ProtoReflect.Descriptor instead.
func (*Novelty) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{10}
}

func (x *Novelty) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type KeyChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // e.g. "C"
	Scale         string                 `protobuf:"bytes,2,opt,name=scale,proto3" json:"scale,omitempty"` // e.g. "major", "minor"
	Strength      float64                `protobuf:"fixed64,3,opt,name=strength,proto3" json:"strength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyChange) Reset() {
	*x = KeyChange{}
	mi := &file_tracks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyChange) ProtoMessage() {}

func (x *KeyChange) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyChange.ProtoReflect.Descriptor instead.
func (*KeyChange) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{11}
}

func (x *KeyChange) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyChange) GetScale() string {
	if x != nil {
		return x.Scale
	}
	return ""
}

func (x *KeyChange) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

type ChordChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chord         string                 `protobuf:"bytes,1,opt,name=chord,proto3" json:"chord,omitempty"` // e.g. "Am", "G"
	Strength      float64                `protobuf:"fixed64,2,opt,name=strength,proto3" json:"strength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChordChange) Reset() {
	*x = ChordChange{}
	mi := &file_tracks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChordChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChordChange) ProtoMessage() {}

func (x *ChordChange) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChordChange.ProtoReflect.Descriptor instead.
func (*ChordChange) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{12}
}

func (x *ChordChange) GetChord() string {
	if x != nil {
		return x.Chord
	}
	return ""
}

func (x *ChordChange) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

type Chroma struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"` // 12-dim HPCP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chroma) Reset() {
	*x = Chroma{}
	mi := &file_tracks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chroma) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chroma) ProtoMessage() {}

func (x *Chroma) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chroma.ProtoReflect.Descriptor instead.
func (*Chroma) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{13}
}

func (x *Chroma) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Tuning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frequency     float64                `protobuf:"fixed64,1,opt,name=frequency,proto3" json:"frequency,omitempty"` // Hz, deviation from A440
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tuning) Reset() {
	*x = Tuning{}
	mi := &file_tracks_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tuning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tuning) ProtoMessage() {}

func (x *Tuning) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tuning.ProtoReflect.Descriptor instead.
func (*Tuning) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{14}
}

func (x *Tuning) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type Dissonance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dissonance) Reset() {
	*x = Dissonance{}
	mi := &file_tracks_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dissonance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dissonance) ProtoMessage() {}

func (x *Dissonance) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dissonance.ProtoReflect.Descriptor instead.
func (*Dissonance) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{15}
}

func (x *Dissonance) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Inharmonicity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inharmonicity) Reset() {
	*x = Inharmonicity{}
	mi := &file_tracks_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inharmonicity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inharmonicity) ProtoMessage() {}

func (x *Inharmonicity) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inharmonicity.ProtoReflect.Descriptor instead.
func (*Inharmonicity) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{16}
}

func (x *Inharmonicity) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Pitch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frequency     float64                `protobuf:"fixed64,1,opt,name=frequency,proto3" json:"frequency,omitempty"` // Hz
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pitch) Reset() {
	*x = Pitch{}
	mi := &file_tracks_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pitch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pitch) ProtoMessage() {}

func (x *Pitch) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pitch.ProtoReflect.Descriptor instead.
func (*Pitch) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{17}
}

func (x *Pitch) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *Pitch) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type PitchChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromHz        float64                `protobuf:"fixed64,1,opt,name=from_hz,json=fromHz,proto3" json:"from_hz,omitempty"`
	ToHz          float64                `protobuf:"fixed64,2,opt,name=to_hz,json=toHz,proto3" json:"to_hz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PitchChange) Reset() {
	*x = PitchChange{}
	mi := &file_tracks_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PitchChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PitchChange) ProtoMessage() {}

func (x *PitchChange) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PitchChange.ProtoReflect.Descriptor instead.
func (*PitchChange) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{18}
}

func (x *PitchChange) GetFromHz() float64 {
	if x != nil {
		return x.FromHz
	}
	return 0
}

func (x *PitchChange) GetToHz() float64 {
	if x != nil {
		return x.ToHz
	}
	return 0
}

type Melody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frequency     float64                `protobuf:"fixed64,1,opt,name=frequency,proto3" json:"frequency,omitempty"` // Hz, predominant pitch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Melody) Reset() {
	*x = Melody{}
	mi := &file_tracks_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Melody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Melody) ProtoMessage() {}

func (x *Melody) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Melody.ProtoReflect.Descriptor instead.
func (*Melody) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{19}
}

func (x *Melody) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type Loudness struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"` // dB or LUFS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Loudness) Reset() {
	*x = Loudness{}
	mi := &file_tracks_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loudness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loudness) ProtoMessage() {}

func (x *Loudness) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loudness.ProtoReflect.Descriptor instead.
func (*Loudness) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{20}
}

func (x *Loudness) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type LoudnessPeak struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoudnessPeak) Reset() {
	*x = LoudnessPeak{}
	mi := &file_tracks_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoudnessPeak) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoudnessPeak) ProtoMessage() {}

func (x *LoudnessPeak) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoudnessPeak.ProtoReflect.Descriptor instead.
func (*LoudnessPeak) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{21}
}

func (x *LoudnessPeak) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Energy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Energy) Reset() {
	*x = Energy{}
	mi := &file_tracks_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Energy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Energy) ProtoMessage() {}

func (x *Energy) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Energy.ProtoReflect.Descriptor instead.
func (*Energy) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{22}
}

func (x *Energy) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DynamicChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magnitude     float64                `protobuf:"fixed64,1,opt,name=magnitude,proto3" json:"magnitude,omitempty"` // size of the dynamic shift
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicChange) Reset() {
	*x = DynamicChange{}
	mi := &file_tracks_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicChange) ProtoMessage() {}

func (x *DynamicChange) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicChange.ProtoReflect.Descriptor instead.
func (*DynamicChange) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{23}
}

func (x *DynamicChange) GetMagnitude() float64 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

type SilenceStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SilenceStart) Reset() {
	*x = SilenceStart{}
	mi := &file_tracks_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SilenceStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SilenceStart) ProtoMessage() {}

func (x *SilenceStart) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SilenceStart.ProtoReflect.Descriptor instead.
func (*SilenceStart) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{24}
}

type SilenceEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SilenceEnd) Reset() {
	*x = SilenceEnd{}
	mi := &file_tracks_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SilenceEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SilenceEnd) ProtoMessage() {}

func (x *SilenceEnd) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SilenceEnd.ProtoReflect.Descriptor instead.
func (*SilenceEnd) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{25}
}

type Gap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      float64                `protobuf:"fixed64,1,opt,name=duration,proto3" json:"duration,omitempty"` // gap duration in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gap) Reset() {
	*x = Gap{}
	mi := &file_tracks_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gap) ProtoMessage() {}

func (x *Gap) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gap.ProtoReflect.Descriptor instead.
func (*Gap) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{26}
}

func (x *Gap) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type SpectralCentroid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpectralCentroid) Reset() {
	*x = SpectralCentroid{}
	mi := &file_tracks_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectralCentroid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectralCentroid) ProtoMessage() {}

func (x *SpectralCentroid) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectralCentroid.ProtoReflect.Descriptor instead.
func (*SpectralCentroid) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{27}
}

func (x *SpectralCentroid) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SpectralFlux struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpectralFlux) Reset() {
	*x = SpectralFlux{}
	mi := &file_tracks_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectralFlux) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectralFlux) ProtoMessage() {}

func (x *SpectralFlux) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectralFlux.ProtoReflect.Descriptor instead.
func (*SpectralFlux) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{28}
}

func (x *SpectralFlux) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SpectralComplexity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpectralComplexity) Reset() {
	*x = SpectralComplexity{}
	mi := &file_tracks_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectralComplexity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectralComplexity) ProtoMessage() {}

func (x *SpectralComplexity) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectralComplexity.ProtoReflect.Descriptor instead.
func (*SpectralComplexity) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{29}
}

func (x *SpectralComplexity) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SpectralContrast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"` // multi-band contrast
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpectralContrast) Reset() {
	*x = SpectralContrast{}
	mi := &file_tracks_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectralContrast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectralContrast) ProtoMessage() {}

func (x *SpectralContrast) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectralContrast.ProtoReflect.Descriptor instead.
func (*SpectralContrast) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{30}
}

func (x *SpectralContrast) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type SpectralRolloff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"` // Hz
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpectralRolloff) Reset() {
	*x = SpectralRolloff{}
	mi := &file_tracks_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectralRolloff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectralRolloff) ProtoMessage() {}

func (x *SpectralRolloff) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectralRolloff.ProtoReflect.Descriptor instead.
func (*SpectralRolloff) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{31}
}

func (x *SpectralRolloff) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Mfcc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"` // 13-dim
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mfcc) Reset() {
	*x = Mfcc{}
	mi := &file_tracks_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mfcc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mfcc) ProtoMessage() {}

func (x *Mfcc) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mfcc.ProtoReflect.Descriptor instead.
func (*Mfcc) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{32}
}

func (x *Mfcc) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type TimbreChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      float64                `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"` // MFCC distance from previous frame
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimbreChange) Reset() {
	*x = TimbreChange{}
	mi := &file_tracks_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimbreChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimbreChange) ProtoMessage() {}

func (x *TimbreChange) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimbreChange.ProtoReflect.Descriptor instead.
func (*TimbreChange) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{33}
}

func (x *TimbreChange) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type BandsMel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandsMel) Reset() {
	*x = BandsMel{}
	mi := &file_tracks_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandsMel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandsMel) ProtoMessage() {}

func (x *BandsMel) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandsMel.ProtoReflect.Descriptor instead.
func (*BandsMel) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{34}
}

func (x *BandsMel) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type BandsBark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandsBark) Reset() {
	*x = BandsBark{}
	mi := &file_tracks_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandsBark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandsBark) ProtoMessage() {}

func (x *BandsBark) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandsBark.ProtoReflect.Descriptor instead.
func (*BandsBark) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{35}
}

func (x *BandsBark) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type BandsErb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandsErb) Reset() {
	*x = BandsErb{}
	mi := &file_tracks_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandsErb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandsErb) ProtoMessage() {}

func (x *BandsErb) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandsErb.ProtoReflect.Descriptor instead.
func (*BandsErb) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{36}
}

func (x *BandsErb) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Hfc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hfc) Reset() {
	*x = Hfc{}
	mi := &file_tracks_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hfc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hfc) ProtoMessage() {}

func (x *Hfc) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hfc.ProtoReflect.Descriptor instead.
func (*Hfc) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{37}
}

func (x *Hfc) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SegmentBoundary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentBoundary) Reset() {
	*x = SegmentBoundary{}
	mi := &file_tracks_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentBoundary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentBoundary) ProtoMessage() {}

func (x *SegmentBoundary) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentBoundary.ProtoReflect.Descriptor instead.
func (*SegmentBoundary) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{38}
}

type FadeIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndTime       float64                `protobuf:"fixed64,1,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"` // when the fade-in ends
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FadeIn) Reset() {
	*x = FadeIn{}
	mi := &file_tracks_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FadeIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FadeIn) ProtoMessage() {}

func (x *FadeIn) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FadeIn.ProtoReflect.Descriptor instead.
func (*FadeIn) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{39}
}

func (x *FadeIn) GetEndTime() float64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type FadeOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     float64                `protobuf:"fixed64,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // when the fade-out starts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FadeOut) Reset() {
	*x = FadeOut{}
	mi := &file_tracks_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FadeOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FadeOut) ProtoMessage() {}

func (x *FadeOut) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FadeOut.ProtoReflect.Descriptor instead.
func (*FadeOut) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{40}
}

func (x *FadeOut) GetStartTime() float64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type Click struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Click) Reset() {
	*x = Click{}
	mi := &file_tracks_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Click) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Click) ProtoMessage() {}

func (x *Click) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Click.ProtoReflect.Descriptor instead.
func (*Click) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{41}
}

type Discontinuity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discontinuity) Reset() {
	*x = Discontinuity{}
	mi := &file_tracks_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discontinuity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discontinuity) ProtoMessage() {}

func (x *Discontinuity) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discontinuity.ProtoReflect.Descriptor instead.
func (*Discontinuity) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{42}
}

type NoiseBurst struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoiseBurst) Reset() {
	*x = NoiseBurst{}
	mi := &file_tracks_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoiseBurst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoiseBurst) ProtoMessage() {}

func (x *NoiseBurst) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoiseBurst.ProtoReflect.Descriptor instead.
func (*NoiseBurst) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{43}
}

type Saturation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      float64                `protobuf:"fixed64,1,opt,name=duration,proto3" json:"duration,omitempty"` // duration of saturation region
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Saturation) Reset() {
	*x = Saturation{}
	mi := &file_tracks_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Saturation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Saturation) ProtoMessage() {}

func (x *Saturation) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Saturation.ProtoReflect.Descriptor instead.
func (*Saturation) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{44}
}

func (x *Saturation) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Hum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frequency     float64                `protobuf:"fixed64,1,opt,name=frequency,proto3" json:"frequency,omitempty"` // Hz of the hum
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hum) Reset() {
	*x = Hum{}
	mi := &file_tracks_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hum) ProtoMessage() {}

func (x *Hum) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hum.ProtoReflect.Descriptor instead.
func (*Hum) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{45}
}

func (x *Hum) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type EnvelopeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeEvent) Reset() {
	*x = EnvelopeEvent{}
	mi := &file_tracks_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeEvent) ProtoMessage() {}

func (x *EnvelopeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeEvent.ProtoReflect.Descriptor instead.
func (*EnvelopeEvent) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{46}
}

func (x *EnvelopeEvent) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Attack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogAttackTime float64                `protobuf:"fixed64,1,opt,name=log_attack_time,json=logAttackTime,proto3" json:"log_attack_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attack) Reset() {
	*x = Attack{}
	mi := &file_tracks_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attack) ProtoMessage() {}

func (x *Attack) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attack.ProtoReflect.Descriptor instead.
func (*Attack) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{47}
}

func (x *Attack) GetLogAttackTime() float64 {
	if x != nil {
		return x.LogAttackTime
	}
	return 0
}

type Decay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decay) Reset() {
	*x = Decay{}
	mi := &file_tracks_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decay) ProtoMessage() {}

func (x *Decay) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decay.ProtoReflect.Descriptor instead.
func (*Decay) Descriptor() ([]byte, []int) {
	return file_tracks_proto_rawDescGZIP(), []int{48}
}

func (x *Decay) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_tracks_proto protoreflect.FileDescriptor

const file_tracks_proto_rawDesc = "" +
	"\n" +
	"\ftracks.proto\x12\x06tracks\"\xf4\x13\n" +
	"\bEnvelope\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x125\n" +
	"\vtrack_start\x18\n" +
	" \x01(\v2\x12.tracks.TrackStartH\x00R\n" +
	"trackStart\x12/\n" +
	"\ttrack_end\x18\v \x01(\v2\x10.tracks.TrackEndH\x00R\btrackEnd\x12>\n" +
	"\x0etrack_position\x18\f \x01(\v2\x15.tracks.TrackPositionH\x00R\rtrackPosition\x125\n" +
	"\vtrack_abort\x18\r \x01(\v2\x12.tracks.TrackAbortH\x00R\n" +
	"trackAbort\x12\"\n" +
	"\x04beat\x18\x14 \x01(\v2\f.tracks.BeatH\x00R\x04beat\x128\n" +
	"\ftempo_change\x18\x15 \x01(\v2\x13.tracks.TempoChangeH\x00R\vtempoChange\x12.\n" +
	"\bdownbeat\x18\x16 \x01(\v2\x10.tracks.DownbeatH\x00R\bdownbeat\x12%\n" +
	"\x05onset\x18\x1e \x01(\v2\r.tracks.OnsetH\x00R\x05onset\x122\n" +
	"\n" +
	"onset_rate\x18\x1f \x01(\v2\x11.tracks.OnsetRateH\x00R\tonsetRate\x12+\n" +
	"\anovelty\x18  \x01(\v2\x0f.tracks.NoveltyH\x00R\anovelty\x122\n" +
	"\n" +
	"key_change\x18( \x01(\v2\x11.tracks.KeyChangeH\x00R\tkeyChange\x128\n" +
	"\fchord_change\x18) \x01(\v2\x13.tracks.ChordChangeH\x00R\vchordChange\x12(\n" +
	"\x06chroma\x18* \x01(\v2\x0e.tracks.ChromaH\x00R\x06chroma\x12(\n" +
	"\x06tuning\x18+ \x01(\v2\x0e.tracks.TuningH\x00R\x06tuning\x124\n" +
	"\n" +
	"dissonance\x18, \x01(\v2\x12.tracks.DissonanceH\x00R\n" +
	"dissonance\x12=\n" +
	"\rinharmonicity\x18- \x01(\v2\x15.tracks.InharmonicityH\x00R\rinharmonicity\x12%\n" +
	"\x05pitch\x182 \x01(\v2\r.tracks.PitchH\x00R\x05pitch\x128\n" +
	"\fpitch_change\x183 \x01(\v2\x13.tracks.PitchChangeH\x00R\vpitchChange\x12(\n" +
	"\x06melody\x184 \x01(\v2\x0e.tracks.MelodyH\x00R\x06melody\x12.\n" +
	"\bloudness\x18< \x01(\v2\x10.tracks.LoudnessH\x00R\bloudness\x12;\n" +
	"\rloudness_peak\x18= \x01(\v2\x14.tracks.LoudnessPeakH\x00R\floudnessPeak\x12(\n" +
	"\x06energy\x18> \x01(\v2\x0e.tracks.EnergyH\x00R\x06energy\x12>\n" +
	"\x0edynamic_change\x18? \x01(\v2\x15.tracks.DynamicChangeH\x00R\rdynamicChange\x12;\n" +
	"\rsilence_start\x18F \x01(\v2\x14.tracks.SilenceStartH\x00R\fsilenceStart\x125\n" +
	"\vsilence_end\x18G \x01(\v2\x12.tracks.SilenceEndH\x00R\n" +
	"silenceEnd\x12\x1f\n" +
	"\x03gap\x18H \x01(\v2\v.tracks.GapH\x00R\x03gap\x12G\n" +
	"\x11spectral_centroid\x18P \x01(\v2\x18.tracks.SpectralCentroidH\x00R\x10spectralCentroid\x12;\n" +
	"\rspectral_flux\x18Q \x01(\v2\x14.tracks.SpectralFluxH\x00R\fspectralFlux\x12M\n" +
	"\x13spectral_complexity\x18R \x01(\v2\x1a.tracks.SpectralComplexityH\x00R\x12spectralComplexity\x12G\n" +
	"\x11spectral_contrast\x18S \x01(\v2\x18.tracks.SpectralContrastH\x00R\x10spectralContrast\x12D\n" +
	"\x10spectral_rolloff\x18T \x01(\v2\x17.tracks.SpectralRolloffH\x00R\x0fspectralRolloff\x12\"\n" +
	"\x04mfcc\x18U \x01(\v2\f.tracks.MfccH\x00R\x04mfcc\x12;\n" +
	"\rtimbre_change\x18V \x01(\v2\x14.tracks.TimbreChangeH\x00R\ftimbreChange\x12/\n" +
	"\tbands_mel\x18Z \x01(\v2\x10.tracks.BandsMelH\x00R\bbandsMel\x122\n" +
	"\n" +
	"bands_bark\x18[ \x01(\v2\x11.tracks.BandsBarkH\x00R\tbandsBark\x12/\n" +
	"\tbands_erb\x18\\ \x01(\v2\x10.tracks.BandsErbH\x00R\bbandsErb\x12\x1f\n" +
	"\x03hfc\x18] \x01(\v2\v.tracks.HfcH\x00R\x03hfc\x12D\n" +
	"\x10segment_boundary\x18d \x01(\v2\x17.tracks.SegmentBoundaryH\x00R\x0fsegmentBoundary\x12)\n" +
	"\afade_in\x18e \x01(\v2\x0e.tracks.FadeInH\x00R\x06fadeIn\x12,\n" +
	"\bfade_out\x18f \x01(\v2\x0f.tracks.FadeOutH\x00R\afadeOut\x12%\n" +
	"\x05click\x18n \x01(\v2\r.tracks.ClickH\x00R\x05click\x12=\n" +
	"\rdiscontinuity\x18o \x01(\v2\x15.tracks.DiscontinuityH\x00R\rdiscontinuity\x125\n" +
	"\vnoise_burst\x18p \x01(\v2\x12.tracks.NoiseBurstH\x00R\n" +
	"noiseBurst\x124\n" +
	"\n" +
	"saturation\x18q \x01(\v2\x12.tracks.SaturationH\x00R\n" +
	"saturation\x12\x1f\n" +
	"\x03hum\x18r \x01(\v2\v.tracks.HumH\x00R\x03hum\x12>\n" +
	"\x0eenvelope_event\x18x \x01(\v2\x15.tracks.EnvelopeEventH\x00R\renvelopeEvent\x12(\n" +
	"\x06attack\x18y \x01(\v2\x0e.tracks.AttackH\x00R\x06attack\x12%\n" +
	"\x05decay\x18z \x01(\v2\r.tracks.DecayH\x00R\x05decayB\a\n" +
	"\x05event\"\x81\x01\n" +
	"\n" +
	"TrackStart\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x01R\bduration\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x04 \x01(\x05R\bchannels\"\n" +
	"\n" +
	"\bTrackEnd\"+\n" +
	"\rTrackPosition\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x01R\bposition\"$\n" +
	"\n" +
	"TrackAbort\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"&\n" +
	"\x04Beat\x12\x1e\n" +
	"\n" +
	"confidence\x18\x01 \x01(\x01R\n" +
	"confidence\"\x1f\n" +
	"\vTempoChange\x12\x10\n" +
	"\x03bpm\x18\x01 \x01(\x01R\x03bpm\"*\n" +
	"\bDownbeat\x12\x1e\n" +
	"\n" +
	"confidence\x18\x01 \x01(\x01R\n" +
	"confidence\"#\n" +
	"\x05Onset\x12\x1a\n" +
	"\bstrength\x18\x01 \x01(\x01R\bstrength\"\x1f\n" +
	"\tOnsetRate\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x01R\x04rate\"\x1f\n" +
	"\aNovelty\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"O\n" +
	"\tKeyChange\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\tR\x05scale\x12\x1a\n" +
	"\bstrength\x18\x03 \x01(\x01R\bstrength\"?\n" +
	"\vChordChange\x12\x14\n" +
	"\x05chord\x18\x01 \x01(\tR\x05chord\x12\x1a\n" +
	"\bstrength\x18\x02 \x01(\x01R\bstrength\" \n" +
	"\x06Chroma\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"&\n" +
	"\x06Tuning\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\x01R\tfrequency\"\"\n" +
	"\n" +
	"Dissonance\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"%\n" +
	"\rInharmonicity\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"E\n" +
	"\x05Pitch\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\x01R\tfrequency\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\";\n" +
	"\vPitchChange\x12\x17\n" +
	"\afrom_hz\x18\x01 \x01(\x01R\x06fromHz\x12\x13\n" +
	"\x05to_hz\x18\x02 \x01(\x01R\x04toHz\"&\n" +
	"\x06Melody\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\x01R\tfrequency\" \n" +
	"\bLoudness\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"$\n" +
	"\fLoudnessPeak\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"\x1e\n" +
	"\x06Energy\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"-\n" +
	"\rDynamicChange\x12\x1c\n" +
	"\tmagnitude\x18\x01 \x01(\x01R\tmagnitude\"\x0e\n" +
	"\fSilenceStart\"\f\n" +
	"\n" +
	"SilenceEnd\"!\n" +
	"\x03Gap\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\x01R\bduration\"(\n" +
	"\x10SpectralCentroid\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"$\n" +
	"\fSpectralFlux\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"*\n" +
	"\x12SpectralComplexity\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"*\n" +
	"\x10SpectralContrast\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"'\n" +
	"\x0fSpectralRolloff\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"\x1e\n" +
	"\x04Mfcc\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"*\n" +
	"\fTimbreChange\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x01R\bdistance\"\"\n" +
	"\bBandsMel\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"#\n" +
	"\tBandsBark\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\"\n" +
	"\bBandsErb\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\x1b\n" +
	"\x03Hfc\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"\x11\n" +
	"\x0fSegmentBoundary\"#\n" +
	"\x06FadeIn\x12\x19\n" +
	"\bend_time\x18\x01 \x01(\x01R\aendTime\"(\n" +
	"\aFadeOut\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x01R\tstartTime\"\a\n" +
	"\x05Click\"\x0f\n" +
	"\rDiscontinuity\"\f\n" +
	"\n" +
	"NoiseBurst\"(\n" +
	"\n" +
	"Saturation\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\x01R\bduration\"#\n" +
	"\x03Hum\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\x01R\tfrequency\"%\n" +
	"\rEnvelopeEvent\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"0\n" +
	"\x06Attack\x12&\n" +
	"\x0flog_attack_time\x18\x01 \x01(\x01R\rlogAttackTime\"\x1d\n" +
	"\x05Decay\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05valueb\x06proto3"

var (
	file_tracks_proto_rawDescOnce sync.Once
	file_tracks_proto_rawDescData []byte
)

func file_tracks_proto_rawDescGZIP() []byte {
	file_tracks_proto_rawDescOnce.Do(func() {
		file_tracks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracks_proto_rawDesc), len(file_tracks_proto_rawDesc)))
	})
	return file_tracks_proto_rawDescData
}

var file_tracks_proto_msgTypes = make([]protoimpl.MessageInfo, 49)
var file_tracks_proto_goTypes = []any{
	(*Envelope)(nil),           // 0: tracks.Envelope
	(*TrackStart)(nil),         // 1: tracks.TrackStart
	(*TrackEnd)(nil),           // 2: tracks.TrackEnd
	(*TrackPosition)(nil),      // 3: tracks.TrackPosition
	(*TrackAbort)(nil),         // 4: tracks.TrackAbort
	(*Beat)(nil),               // 5: tracks.Beat
	(*TempoChange)(nil),        // 6: tracks.TempoChange
	(*Downbeat)(nil),           // 7: tracks.Downbeat
	(*Onset)(nil),              // 8: tracks.Onset
	(*OnsetRate)(nil),          // 9: tracks.OnsetRate
	(*Novelty)(nil),            // 10: tracks.Novelty
	(*KeyChange)(nil),          // 11: tracks.KeyChange
	(*ChordChange)(nil),        // 12: tracks.ChordChange
	(*Chroma)(nil),             // 13: tracks.Chroma
	(*Tuning)(nil),             // 14: tracks.Tuning
	(*Dissonance)(nil),         // 15: tracks.Dissonance
	(*Inharmonicity)(nil),      // 16: tracks.Inharmonicity
	(*Pitch)(nil),              // 17: tracks.Pitch
	(*PitchChange)(nil),        // 18: tracks.PitchChange
	(*Melody)(nil),             // 19: tracks.Melody
	(*Loudness)(nil),           // 20: tracks.Loudness
	(*LoudnessPeak)(nil),       // 21: tracks.LoudnessPeak
	(*Energy)(nil),             // 22: tracks.Energy
	(*DynamicChange)(nil),      // 23: tracks.DynamicChange
	(*SilenceStart)(nil),       // 24: tracks.SilenceStart
	(*SilenceEnd)(nil),         // 25: tracks.SilenceEnd
	(*Gap)(nil),                // 26: tracks.Gap
	(*SpectralCentroid)(nil),   // 27: tracks.SpectralCentroid
	(*SpectralFlux)(nil),       // 28: tracks.SpectralFlux
	(*SpectralComplexity)(nil), // 29: tracks.SpectralComplexity
	(*SpectralContrast)(nil),   // 30: tracks.SpectralContrast
	(*SpectralRolloff)(nil),    // 31: tracks.SpectralRolloff
	(*Mfcc)(nil),               // 32: tracks.Mfcc
	(*TimbreChange)(nil),       // 33: tracks.TimbreChange
	(*BandsMel)(nil),           // 34: tracks.BandsMel
	(*BandsBark)(nil),          // 35: tracks.BandsBark
	(*BandsErb)(nil),           // 36: tracks.BandsErb
	(*Hfc)(nil),                // 37: tracks.Hfc
	(*SegmentBoundary)(nil),    // 38: tracks.SegmentBoundary
	(*FadeIn)(nil),             // 39: tracks.FadeIn
	(*FadeOut)(nil),            // 40: tracks.FadeOut
	(*Click)(nil),              // 41: tracks.Click
	(*Discontinuity)(nil),      // 42: tracks.Discontinuity
	(*NoiseBurst)(nil),         // 43: tracks.NoiseBurst
	(*Saturation)(nil),         // 44: tracks.Saturation
	(*Hum)(nil),                // 45: tracks.Hum
	(*EnvelopeEvent)(nil),      // 46: tracks.EnvelopeEvent
	(*Attack)(nil),             // 47: tracks.Attack
	(*Decay)(nil),              // 48: tracks.Decay
}
var file_tracks_proto_depIdxs = []int32{
	1,  // 0: tracks.Envelope.track_start:type_name -> tracks.TrackStart
	2,  // 1: tracks.Envelope.track_end:type_name -> tracks.TrackEnd
	3,  // 2: tracks.Envelope.track_position:type_name -> tracks.TrackPosition
	4,  // 3: tracks.Envelope.track_abort:type_name -> tracks.TrackAbort
	5,  // 4: tracks.Envelope.beat:type_name -> tracks.Beat
	6,  // 5: tracks.Envelope.tempo_change:type_name -> tracks.TempoChange
	7,  // 6: tracks.Envelope.downbeat:type_name -> tracks.Downbeat
	8,  // 7: tracks.Envelope.onset:type_name -> tracks.Onset
	9,  // 8: tracks.Envelope.onset_rate:type_name -> tracks.OnsetRate
	10, // 9: tracks.Envelope.novelty:type_name -> tracks.Novelty
	11, // 10: tracks.Envelope.key_change:type_name -> tracks.KeyChange
	12, // 11: tracks.Envelope.chord_change:type_name -> tracks.ChordChange
	13, // 12: tracks.Envelope.chroma:type_name -> tracks.Chroma
	14, // 13: tracks.Envelope.tuning:type_name -> tracks.Tuning
	15, // 14: tracks.Envelope.dissonance:type_name -> tracks.Dissonance
	16, // 15: tracks.Envelope.inharmonicity:type_name -> tracks.Inharmonicity
	17, // 16: tracks.Envelope.pitch:type_name -> tracks.Pitch
	18, // 17: tracks.Envelope.pitch_change:type_name -> tracks.PitchChange
	19, // 18: tracks.Envelope.melody:type_name -> tracks.Melody
	20, // 19: tracks.Envelope.loudness:type_name -> tracks.Loudness
	21, // 20: tracks.Envelope.loudness_peak:type_name -> tracks.LoudnessPeak
	22, // 21: tracks.Envelope.energy:type_name -> tracks.Energy
	23, // 22: tracks.Envelope.dynamic_change:type_name -> tracks.DynamicChange
	24, // 23: tracks.Envelope.silence_start:type_name -> tracks.SilenceStart
	25, // 24: tracks.Envelope.silence_end:type_name -> tracks.SilenceEnd
	26, // 25: tracks.Envelope.gap:type_name -> tracks.Gap
	27, // 26: tracks.Envelope.spectral_centroid:type_name -> tracks.SpectralCentroid
	28, // 27: tracks.Envelope.spectral_flux:type_name -> tracks.SpectralFlux
	29, // 28: tracks.Envelope.spectral_complexity:type_name -> tracks.SpectralComplexity
	30, // 29: tracks.Envelope.spectral_contrast:type_name -> tracks.SpectralContrast
	31, // 30: tracks.Envelope.spectral_rolloff:type_name -> tracks.SpectralRolloff
	32, // 31: tracks.Envelope.mfcc:type_name -> tracks.Mfcc
	33, // 32: tracks.Envelope.timbre_change:type_name -> tracks.TimbreChange
	34, // 33: tracks.Envelope.bands_mel:type_name -> tracks.BandsMel
	35, // 34: tracks.Envelope.bands_bark:type_name -> tracks.BandsBark
	36, // 35: tracks.Envelope.bands_erb:type_name -> tracks.BandsErb
	37, // 36: tracks.Envelope.hfc:type_name -> tracks.Hfc
	38, // 37: tracks.Envelope.segment_boundary:type_name -> tracks.SegmentBoundary
	39, // 38: tracks.Envelope.fade_in:type_name -> tracks.FadeIn
	40, // 39: tracks.Envelope.fade_out:type_name -> tracks.FadeOut
	41, // 40: tracks.Envelope.click:type_name -> tracks.Click
	42, // 41: tracks.Envelope.discontinuity:type_name -> tracks.Discontinuity
	43, // 42: tracks.Envelope.noise_burst:type_name -> tracks.NoiseBurst
	44, // 43: tracks.Envelope.saturation:type_name -> tracks.Saturation
	45, // 44: tracks.Envelope.hum:type_name -> tracks.Hum
	46, // 45: tracks.Envelope.envelope_event:type_name -> tracks.EnvelopeEvent
	47, // 46: tracks.Envelope.attack:type_name -> tracks.Attack
	48, // 47: tracks.Envelope.decay:type_name -> tracks.Decay
	48, // [48:48] is the sub-list for method output_type
	48, // [48:48] is the sub-list for method input_type
	48, // [48:48] is the sub-list for extension type_name
	48, // [48:48] is the sub-list for extension extendee
	0,  // [0:48] is the sub-list for field type_name
}

func init() { file_tracks_proto_init() }
func file_tracks_proto_init() {
	if File_tracks_proto != nil {
		return
	}
	file_tracks_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_TrackStart)(nil),
		(*Envelope_TrackEnd)(nil),
		(*Envelope_TrackPosition)(nil),
		(*Envelope_TrackAbort)(nil),
		(*Envelope_Beat)(nil),
		(*Envelope_TempoChange)(nil),
		(*Envelope_Downbeat)(nil),
		(*Envelope_Onset)(nil),
		(*Envelope_OnsetRate)(nil),
		(*Envelope_Novelty)(nil),
		(*Envelope_KeyChange)(nil),
		(*Envelope_ChordChange)(nil),
		(*Envelope_Chroma)(nil),
		(*Envelope_Tuning)(nil),
		(*Envelope_Dissonance)(nil),
		(*Envelope_Inharmonicity)(nil),
		(*Envelope_Pitch)(nil),
		(*Envelope_PitchChange)(nil),
		(*Envelope_Melody)(nil),
		(*Envelope_Loudness)(nil),
		(*Envelope_LoudnessPeak)(nil),
		(*Envelope_Energy)(nil),
		(*Envelope_DynamicChange)(nil),
		(*Envelope_SilenceStart)(nil),
		(*Envelope_SilenceEnd)(nil),
		(*Envelope_Gap)(nil),
		(*Envelope_SpectralCentroid)(nil),
		(*Envelope_SpectralFlux)(nil),
		(*Envelope_SpectralComplexity)(nil),
		(*Envelope_SpectralContrast)(nil),
		(*Envelope_SpectralRolloff)(nil),
		(*Envelope_Mfcc)(nil),
		(*Envelope_TimbreChange)(nil),
		(*Envelope_BandsMel)(nil),
		(*Envelope_BandsBark)(nil),
		(*Envelope_BandsErb)(nil),
		(*Envelope_Hfc)(nil),
		(*Envelope_SegmentBoundary)(nil),
		(*Envelope_FadeIn)(nil),
		(*Envelope_FadeOut)(nil),
		(*Envelope_Click)(nil),
		(*Envelope_Discontinuity)(nil),
		(*Envelope_NoiseBurst)(nil),
		(*Envelope_Saturation)(nil),
		(*Envelope_Hum)(nil),
		(*Envelope_EnvelopeEvent)(nil),
		(*Envelope_Attack)(nil),
		(*Envelope_Decay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracks_proto_rawDesc), len(file_tracks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   49,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tracks_proto_goTypes,
		DependencyIndexes: file_tracks_proto_depIdxs,
		MessageInfos:      file_tracks_proto_msgTypes,
	}.Build()
	File_tracks_proto = out.File
	file_tracks_proto_goTypes = nil
	file_tracks_proto_depIdxs = nil
}
